# permissions for end users to edit helmtestjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helmtestjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: steer-operator
    app.kubernetes.io/part-of: steer-operator
    app.kubernetes.io/managed-by: kustomize
  name: helmtestjob-editor-role
rules:
- apiGroups:
  - steer.steer.io
  resources:
  - helmtestjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - steer.steer.io
  resources:
  - helmtestjobs/status
  verbs:
  - get
