apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "steer.fullname" . }}
  labels:
    {{- include "steer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["steer.io"]
    resources: ["helmreleases", "helmtestjobs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "namespaces"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "steer.fullname" . }}
  labels:
    {{- include "steer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "steer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "steer.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
