apiVersion: v1
kind: Service
metadata:
  name: steer-web
  labels:
    control-plane: controller-manager
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  ports:
  - name: http
    port: 80
    targetPort: web
